/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLamp: typeof import('./components/AppLamp.vue')['default']
    AppTable: typeof import('./components/AppTable/index.vue')['default']
    AppTableContentTooltip: typeof import('./components/AppTable/ContentTooltip.vue')['default']
    AppTableDataTable: typeof import('./components/AppTable/DataTable.vue')['default']
    AppTableOLD_PhotoTable: typeof import('./components/AppTable/OLD_PhotoTable.vue')['default']
    AppTablePhotoTable: typeof import('./components/AppTable/PhotoTable.vue')['default']
    AppTableTable: typeof import('./components/AppTable/Table.vue')['default']
    AppTableTableLoader: typeof import('./components/AppTable/TableLoader.vue')['default']
    AppTableTableSkeleton: typeof import('./components/AppTable/TableSkeleton.vue')['default']
    AppThemeSwitch: typeof import('./components/AppThemeSwitch.vue')['default']
    Lamp: typeof import('./components/Lamp.vue')['default']
    UiButton: typeof import('./components/ui/button/Button.vue')['default']
    UiInput: typeof import('./components/ui/input/Input.vue')['default']
    UiScrollArea: typeof import('./components/ui/scroll-area/ScrollArea.vue')['default']
    UiScrollAreaScrollBar: typeof import('./components/ui/scroll-area/ScrollBar.vue')['default']
    UiSkeleton: typeof import('./components/ui/skeleton/Skeleton.vue')['default']
    UiTable: typeof import('./components/ui/table/Table.vue')['default']
    UiTableBody: typeof import('./components/ui/table/TableBody.vue')['default']
    UiTableCaption: typeof import('./components/ui/table/TableCaption.vue')['default']
    UiTableCell: typeof import('./components/ui/table/TableCell.vue')['default']
    UiTableEmpty: typeof import('./components/ui/table/TableEmpty.vue')['default']
    UiTableFooter: typeof import('./components/ui/table/TableFooter.vue')['default']
    UiTableHead: typeof import('./components/ui/table/TableHead.vue')['default']
    UiTableHeader: typeof import('./components/ui/table/TableHeader.vue')['default']
    UiTableRow: typeof import('./components/ui/table/TableRow.vue')['default']
    UiTooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    UiTooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    UiTooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    UiTooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
